_wandb:
    value:
        cli_version: 0.23.0
        e:
            3mtq9rc1loulix0sx8u1gmp0vtgxeid8:
                codePath: train_02.py
                codePathLocal: train_02.py
                email: mahmoudseddiga@gmail.com
                executable: /usr/bin/python3
                git:
                    commit: aa4074733a923d3b42d4c341cfa7f356f226a940
                    remote: https://github.com/char056a/DeepLearning.git
                host: hpclogin1
                os: Linux-6.1.155-1.el9.elrepo.x86_64-x86_64-with-glibc2.34
                program: /zhome/64/e/180519/DeepLearning/train_02.py
                python: CPython 3.9.21
                root: /zhome/64/e/180519/DeepLearning
                startedAt: "2025-11-22T18:29:10.391191Z"
                writerId: 3mtq9rc1loulix0sx8u1gmp0vtgxeid8
        m: []
        python_version: 3.9.21
        t:
            "3":
                - 16
            "4": 3.9.21
            "5": 0.23.0
            "12": 0.23.0
            "13": linux-x86_64
activation:
    value: Relu
batch_size:
    value: 64
dataset:
    value: Fashion-MNIST
epochs:
    value: 25
hidden_sizes:
    value:
        - 128
        - 64
init:
    value: xavier_uniform
learning_rate:
    value: 0.001
